export const COURSE_PRICE = 1000;

export const AVAILABLE_COURSES = [
  { name: "Advanced Amazon Virtual Assistant", price: COURSE_PRICE },
  { name: "Full Stack Digital Marketing & AI", price: COURSE_PRICE },
  { name: "Advanced Shopify & Daraz", price: COURSE_PRICE },
  { name: "Full Stack Graphic Designing & AI", price: COURSE_PRICE },
  {
    name: "Advanced UIUX Designing with AI for Web & APP",
    price: COURSE_PRICE,
  },
  { name: "WordPress Website Development", price: COURSE_PRICE },
  {
    name: "Full Stack Web Development with React & Node JS",
    price: COURSE_PRICE,
  },
  { name: "MERN Stack Web Development", price: COURSE_PRICE },
  { name: "Advanced PHP Laravel Web Development", price: COURSE_PRICE },
  { name: "Python Programming for Everyone", price: COURSE_PRICE },
  { name: "Web Development with Python Django", price: COURSE_PRICE },
  { name: "Search Engine Optimization - SEO", price: COURSE_PRICE },
  { name: "Advanced Google Ads", price: COURSE_PRICE },
  { name: "National Cyber Security", price: COURSE_PRICE },
  { name: "Penetration Testing Web Hacking", price: COURSE_PRICE },
  { name: "Video Editing & Animation", price: COURSE_PRICE },
  { name: "Artificial Intelligence", price: COURSE_PRICE },
  { name: "Machine Learning & Data Science", price: COURSE_PRICE },
  { name: "Forex Trading", price: COURSE_PRICE },
  { name: "BlockChain Development", price: COURSE_PRICE },
  { name: "Cross platform Flutter App Development", price: COURSE_PRICE },
  { name: "CGI Ads", price: COURSE_PRICE },
  { name: "Architectural Visualization with Blender 3D", price: COURSE_PRICE },
  { name: "Digital Embroidery", price: COURSE_PRICE },
  { name: "Textile Designing", price: COURSE_PRICE },
  { name: "Ielts", price: COURSE_PRICE },
  { name: "Freelancing Program", price: COURSE_PRICE },
];
